### ISSUE TITLE
Set reasonable defaults for in/oubound peers

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#238]
Defaults should support a healthy network.  Inbound peer settings are a limitation that should be addressed

Current values
```toml
# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10
```

Osmosis has:
```toml
# Maximum number of inbound peers
max_num_inbound_peers = 320

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 40
```
